#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Touki Nishi
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)
cal=0
for i in sys.stdin:
    i=i.rstrip()
    cal+=tonum(i)
print(cal)
